export interface ERCase {
  id: number;
  case_name: string;
  category: string;
  esi_level: number;
  severity: 'mild' | 'moderate' | 'severe' | 'critical';
  key_symptoms: string[];
  immediate_action: string[];
  route: string;
  requires_or: boolean;
}

export const ER_CASES: ERCase[] = [
  {"id":1,"case_name":"Cardiac Arrest","category":"Cardiac","esi_level":1,"severity":"critical","key_symptoms":["no pulse","unconscious"],"immediate_action":["CPR","defibrillation"],"route":"Resuscitation Bay","requires_or":false},
  {"id":2,"case_name":"Acute Myocardial Infarction","category":"Cardiac","esi_level":1,"severity":"critical","key_symptoms":["chest pain","sweating"],"immediate_action":["ECG","aspirin"],"route":"Cath Lab","requires_or":true},
  {"id":3,"case_name":"Stroke","category":"Neurology","esi_level":1,"severity":"critical","key_symptoms":["slurred speech","weakness"],"immediate_action":["CT scan"],"route":"Stroke Unit","requires_or":false},
  {"id":4,"case_name":"Severe Head Injury","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["low GCS"],"immediate_action":["intubation"],"route":"CT → OT","requires_or":true},
  {"id":5,"case_name":"Tension Pneumothorax","category":"Chest","esi_level":1,"severity":"critical","key_symptoms":["breathlessness"],"immediate_action":["needle decompression"],"route":"Trauma Bay","requires_or":true},
  {"id":6,"case_name":"Hemorrhagic Shock","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["low BP"],"immediate_action":["blood transfusion"],"route":"OT","requires_or":true},
  {"id":7,"case_name":"Sepsis","category":"Infection","esi_level":1,"severity":"critical","key_symptoms":["fever","low BP"],"immediate_action":["IV antibiotics"],"route":"ICU","requires_or":false},
  {"id":8,"case_name":"Anaphylaxis","category":"Allergy","esi_level":1,"severity":"critical","key_symptoms":["swelling","breathing difficulty"],"immediate_action":["epinephrine"],"route":"Resuscitation","requires_or":false},
  {"id":9,"case_name":"Pulmonary Embolism","category":"Chest","esi_level":1,"severity":"critical","key_symptoms":["sudden dyspnea"],"immediate_action":["anticoagulation"],"route":"ICU","requires_or":false},
  {"id":10,"case_name":"Diabetic Ketoacidosis","category":"Metabolic","esi_level":1,"severity":"critical","key_symptoms":["high sugar"],"immediate_action":["insulin"],"route":"ICU","requires_or":false},
  {"id":11,"case_name":"Epidural Hematoma","category":"Neuro","esi_level":1,"severity":"critical","key_symptoms":["loss of consciousness"],"immediate_action":["CT","surgery"],"route":"OT","requires_or":true},
  {"id":12,"case_name":"Subdural Hematoma","category":"Neuro","esi_level":1,"severity":"critical","key_symptoms":["confusion"],"immediate_action":["CT"],"route":"OT","requires_or":true},
  {"id":13,"case_name":"Spinal Cord Injury","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["paralysis"],"immediate_action":["immobilization"],"route":"ICU","requires_or":true},
  {"id":14,"case_name":"Open Fracture","category":"Orthopedic","esi_level":2,"severity":"severe","key_symptoms":["bone exposed"],"immediate_action":["immobilization"],"route":"OT","requires_or":true},
  {"id":15,"case_name":"Femur Fracture","category":"Orthopedic","esi_level":2,"severity":"severe","key_symptoms":["leg deformity"],"immediate_action":["pain control"],"route":"OT","requires_or":true},
  {"id":16,"case_name":"Burns >40%","category":"Burn","esi_level":1,"severity":"critical","key_symptoms":["burns"],"immediate_action":["fluids"],"route":"Burn ICU","requires_or":true},
  {"id":17,"case_name":"Liver Laceration","category":"Abdominal","esi_level":1,"severity":"critical","key_symptoms":["abdominal pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":18,"case_name":"Splenic Rupture","category":"Abdominal","esi_level":1,"severity":"critical","key_symptoms":["shock"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":19,"case_name":"Kidney Injury","category":"Abdominal","esi_level":2,"severity":"severe","key_symptoms":["blood in urine"],"immediate_action":["CT"],"route":"Urology","requires_or":false},
  {"id":20,"case_name":"Pancreatitis","category":"Abdominal","esi_level":2,"severity":"severe","key_symptoms":["abdominal pain"],"immediate_action":["fluids"],"route":"ICU","requires_or":false},
  {"id":21,"case_name":"Appendicitis","category":"Abdominal","esi_level":2,"severity":"moderate","key_symptoms":["RLQ pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":22,"case_name":"Cholecystitis","category":"Abdominal","esi_level":3,"severity":"moderate","key_symptoms":["RUQ pain"],"immediate_action":["antibiotics"],"route":"Ward","requires_or":true},
  {"id":23,"case_name":"Asthma Attack","category":"Respiratory","esi_level":2,"severity":"severe","key_symptoms":["wheezing"],"immediate_action":["nebulization"],"route":"ER","requires_or":false},
  {"id":24,"case_name":"COPD Exacerbation","category":"Respiratory","esi_level":2,"severity":"severe","key_symptoms":["breathlessness"],"immediate_action":["oxygen"],"route":"ICU","requires_or":false},
  {"id":25,"case_name":"Pneumonia","category":"Respiratory","esi_level":3,"severity":"moderate","key_symptoms":["fever"],"immediate_action":["antibiotics"],"route":"Ward","requires_or":false},
  {"id":26,"case_name":"Seizure","category":"Neurology","esi_level":2,"severity":"severe","key_symptoms":["convulsions"],"immediate_action":["benzodiazepine"],"route":"ER","requires_or":false},
  {"id":27,"case_name":"Migraine","category":"Neurology","esi_level":4,"severity":"mild","key_symptoms":["headache"],"immediate_action":["analgesics"],"route":"OPD","requires_or":false},
  {"id":28,"case_name":"Syncope","category":"General","esi_level":3,"severity":"moderate","key_symptoms":["fainting"],"immediate_action":["monitor"],"route":"ER","requires_or":false},
  {"id":29,"case_name":"Poisoning","category":"Toxicology","esi_level":1,"severity":"critical","key_symptoms":["vomiting"],"immediate_action":["gastric lavage"],"route":"ICU","requires_or":false},
  {"id":30,"case_name":"Snake Bite","category":"Toxicology","esi_level":1,"severity":"critical","key_symptoms":["swelling"],"immediate_action":["antivenom"],"route":"ICU","requires_or":false},
  {"id":31,"case_name":"Aortic Dissection","category":"Vascular","esi_level":1,"severity":"critical","key_symptoms":["tearing chest pain"],"immediate_action":["BP control"],"route":"OT","requires_or":true},
  {"id":32,"case_name":"Deep Vein Thrombosis","category":"Vascular","esi_level":3,"severity":"moderate","key_symptoms":["leg swelling"],"immediate_action":["anticoagulation"],"route":"Ward","requires_or":false},
  {"id":33,"case_name":"Variceal Bleed","category":"GI","esi_level":1,"severity":"critical","key_symptoms":["vomiting blood"],"immediate_action":["endoscopy"],"route":"OT","requires_or":true},
  {"id":34,"case_name":"GI Bleed","category":"GI","esi_level":1,"severity":"critical","key_symptoms":["melena"],"immediate_action":["fluids"],"route":"ICU","requires_or":true},
  {"id":35,"case_name":"Perforation","category":"GI","esi_level":1,"severity":"critical","key_symptoms":["severe pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":36,"case_name":"Pelvic Fracture","category":"Orthopedic","esi_level":1,"severity":"critical","key_symptoms":["pelvic instability"],"immediate_action":["binder"],"route":"OT","requires_or":true},
  {"id":37,"case_name":"Shoulder Dislocation","category":"Orthopedic","esi_level":3,"severity":"moderate","key_symptoms":["joint deformity"],"immediate_action":["reduction"],"route":"ER","requires_or":false},
  {"id":38,"case_name":"Spine Fracture","category":"Orthopedic","esi_level":1,"severity":"critical","key_symptoms":["back pain"],"immediate_action":["immobilization"],"route":"OT","requires_or":true},
  {"id":39,"case_name":"Crush Injury","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["muscle damage"],"immediate_action":["fluids"],"route":"ICU","requires_or":true},
  {"id":40,"case_name":"Polytrauma","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["multiple injuries"],"immediate_action":["ATLS protocol"],"route":"OT","requires_or":true},
  {"id":41,"case_name":"ARDS","category":"Respiratory","esi_level":1,"severity":"critical","key_symptoms":["low oxygen"],"immediate_action":["ventilation"],"route":"ICU","requires_or":false},
  {"id":42,"case_name":"Pleural Effusion","category":"Respiratory","esi_level":3,"severity":"moderate","key_symptoms":["breathlessness"],"immediate_action":["drainage"],"route":"Ward","requires_or":false},
  {"id":43,"case_name":"Lung Contusion","category":"Chest","esi_level":2,"severity":"severe","key_symptoms":["chest pain"],"immediate_action":["oxygen"],"route":"ICU","requires_or":false},
  {"id":44,"case_name":"Hypoglycemia","category":"Metabolic","esi_level":1,"severity":"critical","key_symptoms":["low sugar"],"immediate_action":["glucose"],"route":"ER","requires_or":false},
  {"id":45,"case_name":"Hyperkalemia","category":"Metabolic","esi_level":1,"severity":"critical","key_symptoms":["arrhythmia"],"immediate_action":["calcium gluconate"],"route":"ICU","requires_or":false},
  {"id":46,"case_name":"Renal Failure","category":"Metabolic","esi_level":2,"severity":"severe","key_symptoms":["low urine"],"immediate_action":["dialysis"],"route":"ICU","requires_or":false},
  {"id":47,"case_name":"Heat Stroke","category":"Environmental","esi_level":1,"severity":"critical","key_symptoms":["high temp"],"immediate_action":["cooling"],"route":"ICU","requires_or":false},
  {"id":48,"case_name":"Hypothermia","category":"Environmental","esi_level":1,"severity":"critical","key_symptoms":["low temp"],"immediate_action":["warming"],"route":"ICU","requires_or":false},
  {"id":49,"case_name":"Near Drowning","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["breathing issue"],"immediate_action":["oxygen"],"route":"ICU","requires_or":false},
  {"id":50,"case_name":"Electrocution","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["burns"],"immediate_action":["CPR"],"route":"ICU","requires_or":false},
  {"id":51,"case_name":"Facial Trauma","category":"Trauma","esi_level":2,"severity":"severe","key_symptoms":["bleeding"],"immediate_action":["stabilize airway"],"route":"OT","requires_or":true},
  {"id":52,"case_name":"Eye Injury","category":"Ophthalmology","esi_level":2,"severity":"severe","key_symptoms":["vision loss"],"immediate_action":["eye protection"],"route":"OT","requires_or":true},
  {"id":53,"case_name":"Ear Trauma","category":"ENT","esi_level":3,"severity":"moderate","key_symptoms":["bleeding"],"immediate_action":["cleaning"],"route":"ER","requires_or":false},
  {"id":54,"case_name":"Nasal Fracture","category":"ENT","esi_level":3,"severity":"moderate","key_symptoms":["deformity"],"immediate_action":["reduction"],"route":"ER","requires_or":false},
  {"id":55,"case_name":"Dental Trauma","category":"Dental","esi_level":4,"severity":"mild","key_symptoms":["tooth injury"],"immediate_action":["pain control"],"route":"OPD","requires_or":false},
  {"id":56,"case_name":"UTI Severe","category":"Infection","esi_level":3,"severity":"moderate","key_symptoms":["burning urine"],"immediate_action":["antibiotics"],"route":"Ward","requires_or":false},
  {"id":57,"case_name":"Meningitis","category":"Neuro","esi_level":1,"severity":"critical","key_symptoms":["fever","neck stiffness"],"immediate_action":["IV antibiotics"],"route":"ICU","requires_or":false},
  {"id":58,"case_name":"Encephalitis","category":"Neuro","esi_level":1,"severity":"critical","key_symptoms":["confusion"],"immediate_action":["antivirals"],"route":"ICU","requires_or":false},
  {"id":59,"case_name":"Febrile Seizure","category":"Pediatric","esi_level":2,"severity":"severe","key_symptoms":["fever"],"immediate_action":["antipyretics"],"route":"ER","requires_or":false},
  {"id":60,"case_name":"Neonatal Distress","category":"Pediatric","esi_level":1,"severity":"critical","key_symptoms":["poor breathing"],"immediate_action":["resuscitation"],"route":"NICU","requires_or":false},
  {"id":61,"case_name":"Pediatric Trauma","category":"Pediatric","esi_level":1,"severity":"critical","key_symptoms":["injury"],"immediate_action":["ATLS"],"route":"OT","requires_or":true},
  {"id":62,"case_name":"Allergic Reaction Mild","category":"Allergy","esi_level":4,"severity":"mild","key_symptoms":["rash"],"immediate_action":["antihistamine"],"route":"OPD","requires_or":false},
  {"id":63,"case_name":"Food Poisoning","category":"GI","esi_level":3,"severity":"moderate","key_symptoms":["vomiting"],"immediate_action":["fluids"],"route":"ER","requires_or":false},
  {"id":64,"case_name":"Dehydration","category":"General","esi_level":3,"severity":"moderate","key_symptoms":["dry mouth"],"immediate_action":["IV fluids"],"route":"ER","requires_or":false},
  {"id":65,"case_name":"Hypertensive Crisis","category":"Cardiac","esi_level":1,"severity":"critical","key_symptoms":["high BP"],"immediate_action":["IV meds"],"route":"ICU","requires_or":false},
  {"id":66,"case_name":"Angina","category":"Cardiac","esi_level":2,"severity":"severe","key_symptoms":["chest pain"],"immediate_action":["ECG"],"route":"ER","requires_or":false},
  {"id":67,"case_name":"Arrhythmia","category":"Cardiac","esi_level":2,"severity":"severe","key_symptoms":["irregular pulse"],"immediate_action":["monitor"],"route":"ICU","requires_or":false},
  {"id":68,"case_name":"Pericardial Tamponade","category":"Cardiac","esi_level":1,"severity":"critical","key_symptoms":["shock"],"immediate_action":["pericardiocentesis"],"route":"OT","requires_or":true},
  {"id":69,"case_name":"GI Obstruction","category":"GI","esi_level":2,"severity":"severe","key_symptoms":["vomiting"],"immediate_action":["NG tube"],"route":"OT","requires_or":true},
  {"id":70,"case_name":"Hernia Strangulated","category":"GI","esi_level":1,"severity":"critical","key_symptoms":["pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":71,"case_name":"Testicular Torsion","category":"Urology","esi_level":1,"severity":"critical","key_symptoms":["testicular pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":72,"case_name":"Ectopic Pregnancy","category":"Gynecology","esi_level":1,"severity":"critical","key_symptoms":["abdominal pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":73,"case_name":"Postpartum Hemorrhage","category":"Gynecology","esi_level":1,"severity":"critical","key_symptoms":["bleeding"],"immediate_action":["fluids"],"route":"OT","requires_or":true},
  {"id":74,"case_name":"Ovarian Torsion","category":"Gynecology","esi_level":1,"severity":"critical","key_symptoms":["pain"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":75,"case_name":"Kidney Stone","category":"Urology","esi_level":3,"severity":"moderate","key_symptoms":["flank pain"],"immediate_action":["pain control"],"route":"ER","requires_or":false},
  {"id":76,"case_name":"Urinary Retention","category":"Urology","esi_level":3,"severity":"moderate","key_symptoms":["unable to urinate"],"immediate_action":["catheter"],"route":"ER","requires_or":false},
  {"id":77,"case_name":"Severe Anemia","category":"Hematology","esi_level":2,"severity":"severe","key_symptoms":["fatigue"],"immediate_action":["transfusion"],"route":"Ward","requires_or":false},
  {"id":78,"case_name":"Leukemia Crisis","category":"Hematology","esi_level":1,"severity":"critical","key_symptoms":["bleeding"],"immediate_action":["supportive"],"route":"ICU","requires_or":false},
  {"id":79,"case_name":"Thrombocytopenia","category":"Hematology","esi_level":2,"severity":"severe","key_symptoms":["bleeding"],"immediate_action":["platelets"],"route":"Ward","requires_or":false},
  {"id":80,"case_name":"DIC","category":"Hematology","esi_level":1,"severity":"critical","key_symptoms":["bleeding"],"immediate_action":["plasma"],"route":"ICU","requires_or":false},
  {"id":81,"case_name":"Alcohol Intoxication","category":"Toxicology","esi_level":3,"severity":"moderate","key_symptoms":["confusion"],"immediate_action":["monitor"],"route":"ER","requires_or":false},
  {"id":82,"case_name":"Drug Overdose","category":"Toxicology","esi_level":1,"severity":"critical","key_symptoms":["resp depression"],"immediate_action":["antidote"],"route":"ICU","requires_or":false},
  {"id":83,"case_name":"Carbon Monoxide Poisoning","category":"Toxicology","esi_level":1,"severity":"critical","key_symptoms":["headache"],"immediate_action":["oxygen"],"route":"ICU","requires_or":false},
  {"id":84,"case_name":"Organophosphate Poisoning","category":"Toxicology","esi_level":1,"severity":"critical","key_symptoms":["salivation"],"immediate_action":["atropine"],"route":"ICU","requires_or":false},
  {"id":85,"case_name":"Scorpion Sting","category":"Toxicology","esi_level":2,"severity":"severe","key_symptoms":["pain"],"immediate_action":["antivenom"],"route":"ER","requires_or":false},
  {"id":86,"case_name":"Dog Bite","category":"Trauma","esi_level":3,"severity":"moderate","key_symptoms":["wound"],"immediate_action":["cleaning"],"route":"ER","requires_or":false},
  {"id":87,"case_name":"Laceration","category":"Trauma","esi_level":4,"severity":"mild","key_symptoms":["cut"],"immediate_action":["suturing"],"route":"ER","requires_or":false},
  {"id":88,"case_name":"Minor Burn","category":"Burn","esi_level":4,"severity":"mild","key_symptoms":["redness"],"immediate_action":["cooling"],"route":"OPD","requires_or":false},
  {"id":89,"case_name":"Foreign Body Ingestion","category":"GI","esi_level":2,"severity":"severe","key_symptoms":["choking"],"immediate_action":["endoscopy"],"route":"OT","requires_or":true},
  {"id":90,"case_name":"Foreign Body Aspiration","category":"Respiratory","esi_level":1,"severity":"critical","key_symptoms":["choking"],"immediate_action":["bronchoscopy"],"route":"OT","requires_or":true},
  {"id":91,"case_name":"Eye Chemical Injury","category":"Ophthalmology","esi_level":1,"severity":"critical","key_symptoms":["burning"],"immediate_action":["irrigation"],"route":"ER","requires_or":false},
  {"id":92,"case_name":"Acute Glaucoma","category":"Ophthalmology","esi_level":2,"severity":"severe","key_symptoms":["eye pain"],"immediate_action":["medication"],"route":"ER","requires_or":false},
  {"id":93,"case_name":"Retinal Detachment","category":"Ophthalmology","esi_level":2,"severity":"severe","key_symptoms":["vision loss"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":94,"case_name":"Epistaxis Severe","category":"ENT","esi_level":2,"severity":"severe","key_symptoms":["nose bleed"],"immediate_action":["packing"],"route":"ER","requires_or":false},
  {"id":95,"case_name":"Airway Obstruction","category":"Respiratory","esi_level":1,"severity":"critical","key_symptoms":["no airflow"],"immediate_action":["intubation"],"route":"Resuscitation","requires_or":true},
  {"id":96,"case_name":"Traumatic Amputation","category":"Trauma","esi_level":1,"severity":"critical","key_symptoms":["limb loss"],"immediate_action":["control bleeding"],"route":"OT","requires_or":true},
  {"id":97,"case_name":"Compartment Syndrome","category":"Orthopedic","esi_level":1,"severity":"critical","key_symptoms":["pain"],"immediate_action":["fasciotomy"],"route":"OT","requires_or":true},
  {"id":98,"case_name":"Gas Gangrene","category":"Infection","esi_level":1,"severity":"critical","key_symptoms":["tissue necrosis"],"immediate_action":["surgery"],"route":"OT","requires_or":true},
  {"id":99,"case_name":"Necrotizing Fasciitis","category":"Infection","esi_level":1,"severity":"critical","key_symptoms":["severe pain"],"immediate_action":["debridement"],"route":"OT","requires_or":true},
  {"id":100,"case_name":"Mass Casualty Trauma","category":"Disaster","esi_level":1,"severity":"critical","key_symptoms":["multiple patients"],"immediate_action":["triage"],"route":"Multiple","requires_or":true}
];
